### ISSUE TITLE
barcode setting

### ISSUE THREAD

**Issue by Jarvis559** [y9c/pseudoU-BIDseq#10]
Hi y9c!
I have a question here. I use the R2 reads for your pipeline，and there are 8nt UMI and 6nt random sequence in the 5' end, and i have already trimmed the 3' end adapter, how should i set the barcode,  is "NNNNNNNNXXXXXX-" work? Looking forward to your reply, thanks!

**Comment by y9c** [comment]
Hi @Jarvis559, Yes. "NNNNNNNNXXXXXX-" should work. You can test it and if there is any issue, please let me know. Thank you.
