### ISSUE TITLE
Long running time

### ISSUE THREAD

**Issue by jingangdidi** [y9c/pseudoU-BIDseq#13]
Hi y9c,
I run the pipeline for 3 input (mESC-WT_polyA-RNA_Input_rep1/2/3.fastq) and 3 treat (mESC-WT_polyA-RNA_Treated_rep1/2/3.fastq), run with 48 cores, the bowtie2 has a long running time in mapping_unsort (mESCWT-rep2-treated_run1_genes.fq has been running for 24 hours).
I read your paper, it's say "sequencing data processing and mutation calling: ~4 h", is this ok? Thanks a lot!

**Comment by y9c** [comment]
Yes. The bowtie2 is extremely slow, especially when the number of rRNA reads is high. You can try `speedy_mapping: true` in your config file to speed up.

**Comment by jingangdidi** [comment]
Hi y9c,
I got "Successfully finished all jobs.", in "call_sites" and "filter_sites" folder, all tsv files do not contain motif sequence, but your paper said "Each row in the table provides essential information about a specific Ψ site, including its genomic coordinates and the surrounding motif sequence.". How can I get the motif sequence? Thanks a lot!
![14](https://github.com/user-attachments/assets/da59db6b-f391-4967-b33e-4e52edb6d53d)

**Comment by y9c** [comment]
Yes. I did not include gene annotation in the updated version to make it more applicable to species beyond just humans and mice. You can complete the gene annotation using R or any other tools you prefer.
