### ISSUE TITLE
multiple mapping reads

### ISSUE THREAD

**Issue by Jarvis559** [y9c/pseudoU-BIDseq#16]
Hi, I notice that the STAR parameter for multiple mapping reads  is to keep all the highest score alignments, 

--outFilterMultimapNmax 10 \
--outFilterMultimapScoreRange 0 \
--outSAMmultNmax -1 \
--outMultimapperOrder Random \

and the flagstat of bam file can also illustrate this situation，

47981434 + 0 in total (QC-passed reads + QC-failed reads)
15647493 + 0 secondary
200692 + 0 supplementary
0 + 0 duplicates
47981434 + 0 mapped (100.00% : N/A)
0 + 0 paired in sequencing
0 + 0 read1
0 + 0 read2
0 + 0 properly paired (N/A : N/A)
0 + 0 with itself and mate mapped
0 + 0 singletons (N/A : N/A)
0 + 0 with mate mapped to a different chr
0 + 0 with mate mapped to a different chr (mapQ>=5)

so I want to know how the pipeline deals with the multiple mapping alignments, just keep the random highest mapping score alignment for one read? Thank you.

**Comment by y9c** [comment]
Thank you for your interst in the pipeline. You can refer to https://github.com/y9c/pseudoU-BIDseq/issues/15.
