### ISSUE TITLE
Low mapping ratio and lost reads after realigngap and filter

### ISSUE THREAD

**Issue by erhei01** [y9c/pseudoU-BIDseq#3]
Hi y9c!
I am trying your pseudoU-BIDseq pipeline. I found your workflow is very efficient and your coding is perfect.Nice work!
I have a question here. when I ran the pipeline with the mRNA samples from _Quantitative sequencing using BID-seq uncovers abundant pseudouridines in mammalian mRNA at base resolution_, I found the mapping ratio for genome is very low(~30% for unique mapping and ~6 % for multimapping), and I have lost lots of reads after realignGap and _samtools calmd, samtools view -e '[NM]<=5 && [NM]/(qlen-sclen)<=0.1'_, the average of lost reads is about 40%.
I wonder is this correct and what can I do?
Thanks you!

**Comment by y9c** [comment]
Thank you @erhei01. Low mapping ratio might caused by improperly adapter trimming. Could you show me which dataset you have tested and the adapter in your settings?

**Comment by erhei01** [comment]
Thanks for your reply.
I ran your Snakefile with default settings on SRR15082607~SRR15082610 of GSE179798 and I found the deduping and mapping records in workspace/report_reads directory.

**Comment by y9c** [comment]
The default settings of this repo do not fit the data you mentioned. This method is quite different from the previous paper. If you want to reproduce the results, I would recommend you to follow the method described in the paper. 

This parameters can be modified to fit those data by adding `barcode: NNNNNXXX-XXXNNNNNATCACG` in the yaml file. If you use the default settings, the inline barcode won't be trimmed and lead to low mapping ratio. 

If you have any questions or suggestions, feel free to open new issues.
