### ISSUE TITLE
Filtering question

### ISSUE THREAD

**Issue by sme996** [y9c/pseudoU-BIDseq#5]
Hello, I recently used your BIDseq workflow and analysis pipeline - it is very straightforward to use, thank you for making it easily accessible! 

I had one question about the filtering aspect of the pipeline. From what I can tell, the filter_sites contain sites that would be filtered out by the filter parameters published in Dai et al 2022 ((1) deletion rate above 5% (with deletion count above five in BID-seq libraries); (2) deletion rate below 1% in ‘Input’ libraries; (3) total reads coverage depth above 20 in both BID-seq and ‘Input’ libraries; (4) deletion rate above 1.5-fold over background in any given sequence motif (defined as the deletion rates detected from RNA probes containing 0% Ψ,). Would you recommend to use those parameters to further filter the output sites? 

Thanks!

**Comment by y9c** [comment]
Hi @sme996, you can tried these cutoffs. However, the cutoffs should based on the data quality and the pu level of your samples. You can adjust these parameters if you find better combinations.
