### ISSUE TITLE
header of result 

### ISSUE THREAD

**Issue by hanguojun007** [y9c/pseudoU-BIDseq#7]
Hi @y9c , thanks very much! 
i have got the final result. but i don't know what mean is the `depth`, `gap`,`WT_ratio`,`WT_fraction`. could you give me a detailed explanation ?
[genome.zip](https://github.com/y9c/pseudoU-BIDseq/files/13346378/genome.zip)

**Comment by y9c** [comment]
Hello,

In this dataset, the "depth" column represents the count of reads that cover a specific site, while the "gap" column signifies the count of reads containing gaps within that site. The "WT_ratio" column calculates the ratio of gaps to the depth for the WT sample, providing a measure of relative gap prevalence. Finally, the "WT_fraction" column represents the fraction of modification for the WT sample, taking into account the application of calibration curves.
